name: Team Membership Tests

on:
  workflow_dispatch:

jobs:
  read-only-app:
    name: Read-Only App
    runs-on: ubuntu-latest

    steps:
      - name: Get GitHub App Token
        id: token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.READ_ONLY_APP_ID }}
          private-key: ${{ secrets.READ_ONLY_APP_PEM_FILE }}
          owner: ${{ github.repository_owner }}

      - name: Get Team Membership
        id: team-membership
        uses: ncalteen-avocado/org-team-membership-test@main
        with:
          app_name: Read
          token_name: Read
          token: ${{ steps.token.outputs.token }}

  read-write-app:
    name: Read-Write App
    runs-on: ubuntu-latest

    steps:
      - name: Get GitHub App Token
        id: token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.READ_WRITE_APP_ID }}
          private-key: ${{ secrets.READ_WRITE_APP_PEM_FILE }}
          owner: ${{ github.repository_owner }}

      - name: Get Team Membership
        id: team-membership
        uses: ncalteen-avocado/org-team-membership-test@main
        with:
          app_name: Read
          token_name: Read
          token: ${{ steps.token.outputs.token }}
